### ISSUE TITLE
`deploy-succeeded` lambda is broken: unknown error

### ISSUE THREAD

**Issue by bellangerq** [bellangerq/personal-website-2022#5]
Here is the error from the Netlify function log:

```sh
11:47:34 AM 2022-07-21T09:47:34.342Z	undefined	ERROR	Uncaught Exception 	{"errorType":"TypeError","errorMessage":"Class extends value #<Object> is not a constructor or null","stack":["TypeError: Class extends value #<Object> is not a constructor or null","    at Object.<anonymous> (/var/task/node_modules/fetch-blob/file.js:59:18)","    at Module._compile (node:internal/modules/cjs/loader:1105:14)","    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)","    at Module.load (node:internal/modules/cjs/loader:981:32)","    at Function.Module._load (node:internal/modules/cjs/loader:822:12)","    at Module.require (node:internal/modules/cjs/loader:1005:19)","    at require (node:internal/modules/cjs/helpers:102:18)","    at Object.<anonymous> (/var/task/node_modules/formdata-polyfill/esm.min.js:35:27)","    at Module._compile (node:internal/modules/cjs/loader:1105:14)","    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)"]}
11:47:34 AM 2022-07-21T09:47:34.687Z	undefined	ERROR	Uncaught Exception 	{"errorType":"TypeError","errorMessage":"Class extends value #<Object> is not a constructor or null","stack":["TypeError: Class extends value #<Object> is not a constructor or null","    at Object.<anonymous> (/var/task/node_modules/fetch-blob/file.js:59:18)","    at Module._compile (node:internal/modules/cjs/loader:1105:14)","    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)","    at Module.load (node:internal/modules/cjs/loader:981:32)","    at Function.Module._load (node:internal/modules/cjs/loader:822:12)","    at Module.require (node:internal/modules/cjs/loader:1005:19)","    at require (node:internal/modules/cjs/helpers:102:18)","    at Object.<anonymous> (/var/task/node_modules/formdata-polyfill/esm.min.js:35:27)","    at Module._compile (node:internal/modules/cjs/loader:1105:14)","    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)"]}
11:47:34 AM 3763caeb Duration: 301.67 ms	Memory Usage: 18 MB
11:47:34 AM Unknown application error occurred
TypeError
```

And the related JS function: [functions/deploy-succeeded.js](https://github.com/bellangerq/personal-website-2022/blob/main/functions/deploy-succeeded.js).

**Comment by bellangerq** [comment]
Quick Google search shows that the problem may be related with import statement or circular reference.
